title: Welcome! I'm Steve
name: Steve Lee
email: slee279@illinois.edu
description: I’m a performance-driven data scientist and an extreme sabermetrics fan. I am a firm believer that data and statistics can improve the quality of life and drive practical solutions to the team. I value attention to details and results in data science. My programming skills and background in statistics have helped me to find the real power of data science and to produce tangible results.

#Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.

baseurl: "/blog"
url: ""

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: "ACT vs SAT"
project_one_description: Describe your project!
project_one_url: https://github.com/slee279/ACT_SAT_Comparison

project_two: "Ames Housing Price"
project_two_description: Describe your project!
project_two_url: https://github.com/slee279/Ames

project_three: "Reddit API"
project_three_description: Describe your project!
project_three_url: https://github.com/slee279/Reddit

project_four: "West Nile Virus in Chicago"
project_four_description: Describe your project!
project_four_url: https://github.com/slee279/WMV

project_five: "Predicting EPL 18/19"
project_five_description: Describe your project!
project_five_url: https://github.com/slee279/EPL

project_six: "Donut Delights"
project_six_description: Describe your project!
project_six_url: https://slee279.github.io/donut

portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true

project_button: Github

github: https://github.com/slee279
medium: https://slee279.github.io/online-cv/

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: https://slee279.github.io/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: UA-77280779-2 # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
